version: "3.7"
services:
  db:
    image: mongo
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb
    ports:
      - 27017:27017
    environment:
      TZ: "Europe/Tallinn"
    networks:
      - backend

  protokollitaja-backend:
    image: protokollitaja-backend
    volumes:
      - /data:/data
    ports:
      - 3005:3005
    environment:
      TZ: "Europe/Tallinn"
    env_file:
      - ./../protokollitaja-backend.env
    container_name: protokollitaja-backend
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:

volumes:
  mongo-data:
    name: mongo-data
  mongo-configdb:
    name: mongo-configdb