version: "3.7"
services:
  db:
    image: mongo
    container_name: mongodb

  protokollitaja-backend:
    image: protokollitaja-backend
    volumes:
      - /data:/data
      - mongo-data:/data/db
    ports:
      - 3005:3005
    env_file:
      - ./../protokollitaja-backend.env
    container_name: protokollitaja-backend
    depends_on:
      - db
    links:
      - db

volumes:
  mongo-data: