services:
  db:
    image: mongo
    restart: unless-stopped
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb
      - /data/protokollitaja-backup:/backup
    ports:
      - 27017:27017
    environment:
      TZ: "Europe/Tallinn"
    networks:
      - backend-dev

  protokollitaja-backend:
    image: protokollitaja-backend
    volumes:
      - /data:/data
    ports:
      - 3004:3004
      - 3005:3005
    environment:
      TZ: "Europe/Tallinn"
    env_file:
      - ./../protokollitaja-backend.env.development
    container_name: protokollitaja-backend
    depends_on:
      - db
    networks:
      - backend-dev

networks:
  backend-dev:

volumes:
  mongo-data:
    name: mongo-data
  mongo-configdb:
    name: mongo-configdb